const PROVIDERS={
  'milora-mambo':{name:'Milora 曼波免费版',endpoint:'https://api.milorapart.top/apis/mbAIsc',model:'曼波免费试用版'},
  'fish-audio':{name:'Fish Audio',endpoint:'https://api.fish.audio/v1/tts',model:'s2.1-pro-free'},
  'aliyun-qwen-tts':{name:'阿里云 Qwen-TTS',endpoint:'https://dashscope.aliyuncs.com/api/v1',model:'qwen3-tts-vc-2026-01-22'},
  custom:{name:'自定义接口',endpoint:'',model:''}
};
const STORAGE='voiceprint-pwa-settings-v1',HISTORY='voiceprint-pwa-history-v1';
const $=id=>document.getElementById(id);
const state={settings:loadSettings(),reference:null,referenceUrl:null,recorder:null,chunks:[],generatedBlob:null,generatedUrl:null,generating:false};
function loadSettings(){const base={activeProvider:'milora-mambo',profiles:{}};try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'{}');base.activeProvider=saved.activeProvider||base.activeProvider;base.profiles=saved.profiles||{};return base}catch{return base}}
function profile(key=state.settings.activeProvider){return {...PROVIDERS[key],...(state.settings.profiles[key]||{}),provider:key}}
function saveSettings(){localStorage.setItem(STORAGE,JSON.stringify(state.settings))}
function toast(message,type=''){const node=document.createElement('div');node.className='toast '+type;node.textContent=message;$('toastRegion').appendChild(node);setTimeout(()=>node.remove(),3600)}
function setStatus(text){$('activeStatus').textContent='当前接口：'+text}
function activeName(){return PROVIDERS[state.settings.activeProvider]?.name||state.settings.activeProvider}
function updateStatus(){setStatus(activeName())}
function updateReference(file,source){if(state.referenceUrl)URL.revokeObjectURL(state.referenceUrl);state.reference=file;state.referenceUrl=URL.createObjectURL(file);$('referenceCard').classList.remove('empty');$('referenceName').textContent=file.name;$('referenceMeta').textContent=source+' · '+formatBytes(file.size);$('referenceBadge').textContent='已准备'}
function formatBytes(n){return n<1024?`${n} B`:`${(n/1024/1024).toFixed(1)} MB`}
function audioExt(){return state.reference?.name?.split('.').pop()?.toLowerCase()||'m4a'}
function notifyDone(){
  if(navigator.vibrate)navigator.vibrate([40,30,40]);
  if(!('Notification' in window)||Notification.permission!=='granted')return;
  const show=registration=>registration?.showNotification?.('声纹工坊：生成完成',{body:'音频已经准备好，可以试听或下载。'});
  if(state.serviceWorkerRegistration)state.serviceWorkerRegistration.then(show).catch(()=>{});
  else if('serviceWorker' in navigator)navigator.serviceWorker.ready.then(show).catch(()=>{});
}
function renderHistory(){const items=JSON.parse(localStorage.getItem(HISTORY)||'[]');const el=$('historyList');if(!items.length){el.innerHTML='<div class="empty-state">还没有生成记录</div>';return}el.innerHTML=items.slice(0,12).map((h,i)=>`<div class="history-item"><div><strong>${escapeHtml(h.text)}</strong><small>${h.provider} · ${h.time} · ${h.speed}× · ${h.emotion}</small></div><button class="history-play" data-index="${i}">载入</button></div>`).join('');el.querySelectorAll('.history-play').forEach(btn=>btn.onclick=()=>{const h=items[Number(btn.dataset.index)];if(h.url){$('audioPlayer').src=h.url;$('resultTitle').textContent='历史音频';$('resultMeta').textContent=h.time;$('resultCard').classList.remove('hidden');state.generatedUrl=h.url;toast('已载入历史音频','success')}else toast('历史文件只保留在生成当次浏览器会话中，请重新生成','error')})}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function saveHistory(text,provider,speed,emotion,url){const items=JSON.parse(localStorage.getItem(HISTORY)||'[]');items.unshift({text,provider:PROVIDERS[provider]?.name||provider,speed,emotion,time:new Date().toLocaleString(),url});localStorage.setItem(HISTORY,JSON.stringify(items.slice(0,30)));renderHistory()}
async function blobFromUrl(url){const response=await fetch(String(url).replace(/^http:\/\//,'https://'));if(!response.ok)throw new Error(`音频下载失败（${response.status}）`);return await response.blob()}
async function generateMilora(text,p){const url=new URL('/api/milora',window.location.origin);url.searchParams.set('text',text);const r=await fetch(url);if(!r.ok){let message='Milora 代理请求失败';try{message=(await r.json()).error||message}catch{}throw new Error(message)}return r.blob();}
async function generateFish(text,p){if(!p.apiKey)throw new Error('Fish Audio 需要 API Key');if(!p.voiceId)throw new Error('Fish Audio 需要 Voice ID / reference_id');const r=await fetch(p.endpoint||PROVIDERS['fish-audio'].endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${p.apiKey}`,model:p.model||'s2.1-pro-free'},body:JSON.stringify({text,reference_id:p.voiceId,prosody:{speed:Number($('speedInput').value),volume:0,normalize_loudness:true},format:'mp3',normalize:true})});const type=r.headers.get('content-type')||'';if(!r.ok)throw new Error(type.includes('json')?((await r.json()).message||'Fish Audio 请求失败'):`Fish Audio 请求失败（${r.status}）`);return r.blob()}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
async function generateAliyun(text,p){if(!p.apiKey)throw new Error('阿里云需要 API Key');if(!state.reference)throw new Error('阿里云声音复刻需要参考音频');const mime=(state.reference.type||'').toLowerCase();const name=(state.reference.name||'').toLowerCase();const supported=mime.includes('mpeg')||mime.includes('mp4')||mime.includes('wav')||/\.(mp3|m4a|wav)$/.test(name);if(!supported)throw new Error('当前参考音频不是阿里云支持的 MP3、M4A 或 WAV 格式，请改用这三种格式');const audio=await fileToDataUrl(state.reference);const root=p.endpoint||PROVIDERS['aliyun-qwen-tts'].endpoint;const headers={'Content-Type':'application/json',Authorization:`Bearer ${p.apiKey}`};const clone=await fetch(root+'/services/audio/tts/customization',{method:'POST',headers,body:JSON.stringify({model:'qwen-voice-enrollment',input:{action:'create',target_model:p.model||'qwen3-tts-vc-2026-01-22',preferred_name:'voice'+Date.now().toString().slice(-8),audio:{data:audio},language:'zh'}})});const cd=await clone.json();const voice=cd.output?.voice||cd.output?.voice_id;if(!voice)throw new Error('阿里云未返回 Voice ID：'+JSON.stringify(cd).slice(0,180));const r=await fetch(root+'/services/aigc/multimodal-generation/generation',{method:'POST',headers,body:JSON.stringify({model:p.model||'qwen3-tts-vc-2026-01-22',input:{text,voice,language_type:'Chinese',instructions:`请用${$('emotionInput').value}的情感表达，语速${Number($('speedInput').value)<1?'偏慢':Number($('speedInput').value)>1?'偏快':'适中'}。`}})});const data=await r.json();if(!r.ok)throw new Error(data.message||'阿里云合成失败');const url=data.output?.audio?.url||data.output?.url||data.url;if(!url)throw new Error('阿里云未返回音频地址');return blobFromUrl(url)}
async function generateCustom(text,p){if(!p.endpoint)throw new Error('请先填写自定义 Endpoint');const r=await fetch(p.endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(p.apiKey?{Authorization:`Bearer ${p.apiKey}`}:{})},body:JSON.stringify({text,model:p.model,voice_id:p.voiceId,reference_id:p.voiceId,speed:Number($('speedInput').value),emotion:$('emotionInput').value})});if(!r.ok)throw new Error(`自定义接口请求失败（${r.status}）`);const type=r.headers.get('content-type')||'';if(type.includes('json')){const data=await r.json();const url=data.audio_url||data.url||data.output?.audio?.url;if(!url)throw new Error('自定义接口未返回 audio_url/url');return blobFromUrl(url)}return r.blob()}
async function generate(){if(state.generating)return;const text=$('textInput').value.trim();if(!text){toast('请输入要合成的文案','error');return}const p=profile();if(p.provider!=='milora-mambo'&&!state.reference&&!p.voiceId){toast('请先选择或录制参考音频','error');return}state.generating=true;const button=$('generateButton');button.disabled=true;button.innerHTML='<span>正在生成，请稍候…</span><span class="spinner">◌</span>';$('resultCard').classList.add('hidden');try{let result;if(p.provider==='milora-mambo')result={blob:await generateMilora(text,p)};else if(p.provider==='fish-audio')result={blob:await generateFish(text,p)};else if(p.provider==='aliyun-qwen-tts')result={blob:await generateAliyun(text,p)};else result={blob:await generateCustom(text,p)};if(state.generatedUrl&&!state.generatedRemoteUrl)URL.revokeObjectURL(state.generatedUrl);state.generatedBlob=result.blob||null;state.generatedRemoteUrl=result.remoteUrl||null;state.generatedUrl=result.remoteUrl||URL.createObjectURL(result.blob);$('audioPlayer').src=state.generatedUrl;$('resultTitle').textContent='生成完成';$('resultMeta').textContent=result.remoteUrl?`${activeName()} · 在线音频已准备好`:`${activeName()} · ${formatBytes(result.blob.size)}`;$('resultCard').classList.remove('hidden');saveHistory(text,p.provider,Number($('speedInput').value).toFixed(2),$('emotionInput').value,state.generatedUrl);toast('生成完成，可以试听或下载','success');notifyDone()}catch(error){$('resultTitle').textContent='生成失败';$('resultMeta').textContent=error.message||String(error);toast(error.message||'生成失败','error')}finally{state.generating=false;button.disabled=false;button.innerHTML='<span>生成试听</span><span>→</span>'}}
function renderSettings(){const p=profile();$('endpointInput').value=p.endpoint||'';$('apiKeyInput').value=p.apiKey||'';$('modelInput').value=p.model||'';$('voiceInput').value=p.voiceId||'';$('outputInput').value=p.outputDir||'';document.querySelectorAll('.provider-tab').forEach(btn=>btn.classList.toggle('active',btn.dataset.provider===state.settings.activeProvider));}
function openSettings(){renderSettings();$('settingsBackdrop').classList.remove('hidden');document.body.classList.add('modal-open')}
function closeSettings(){document.activeElement?.blur();$('settingsBackdrop').classList.add('hidden');document.body.classList.remove('modal-open')}
function saveSettingsFromForm(){const key=state.settings.activeProvider;state.settings.profiles[key]={...profile(key),endpoint:$('endpointInput').value.trim(),apiKey:$('apiKeyInput').value,model:$('modelInput').value.trim(),voiceId:$('voiceInput').value.trim(),outputDir:$('outputInput').value.trim()};saveSettings();updateStatus();toast(`${PROVIDERS[key].name} 配置已保存`,'success');$('settingsSave').textContent='已保存 ✓';setTimeout(()=>$('settingsSave').textContent='保存当前配置',1400)}
function bind(){
  $('settingsOpen').onclick=openSettings;$('settingsOpen2').onclick=openSettings;$('settingsClose').onclick=closeSettings;$('settingsCancel').onclick=closeSettings;$('settingsBackdrop').onclick=e=>{if(e.target===$('settingsBackdrop'))closeSettings()};$('settingsSave').onclick=saveSettingsFromForm;
  $('providerTabs').innerHTML=Object.entries(PROVIDERS).map(([key,p])=>`<button class="provider-tab" data-provider="${key}">${p.name}</button>`).join('');document.querySelectorAll('.provider-tab').forEach(btn=>btn.onclick=()=>{state.settings.activeProvider=btn.dataset.provider;renderSettings()});
  $('fileButton').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>{const file=e.target.files?.[0];if(file)updateReference(file,'本地文件');e.target.value=''};
  $('recordButton').onclick=async()=>{if(state.recorder&&state.recorder.state==='recording'){state.recorder.stop();$('recordLabel').textContent='正在保存录音…';return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=MediaRecorder.isTypeSupported('audio/mp4')?'audio/mp4':MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':'audio/ogg';state.chunks=[];state.recorder=new MediaRecorder(stream,{mimeType:mime});state.recorder.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data)};state.recorder.onstop=()=>{stream.getTracks().forEach(track=>track.stop());const ext=mime.includes('mp4')?'m4a':mime.includes('webm')?'webm':'ogg';updateReference(new File(state.chunks,`reference-${Date.now()}.${ext}`,{type:mime}),'刚刚录音');$('recordLabel').textContent='开始录音'};state.recorder.start();$('recordLabel').textContent='停止录音';toast('正在录音，再次点击停止','success')}catch(error){toast('无法录音：请允许浏览器访问麦克风','error')}};
  $('speedInput').oninput=e=>$('speedValue').textContent=Number(e.target.value).toFixed(2)+'×';$('generateButton').onclick=generate;$('downloadButton').onclick=()=>{if(!state.generatedUrl)return;if(state.generatedRemoteUrl){window.open(state.generatedRemoteUrl,'_blank','noopener');toast('已打开音频地址，请用 Safari 分享菜单存储到“文件”','success');return}const a=document.createElement('a');a.href=state.generatedUrl;a.download=`voiceprint-${Date.now()}.mp3`;a.click();toast('已开始下载','success')};$('shareButton').onclick=async()=>{if(state.generatedRemoteUrl){window.open(state.generatedRemoteUrl,'_blank','noopener');toast('已打开音频地址，请使用 Safari 分享菜单保存或分享','success');return}if(!state.generatedBlob)return;const file=new File([state.generatedBlob],`voiceprint-${Date.now()}.mp3`,{type:state.generatedBlob.type||'audio/mpeg'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({title:'声纹工坊音频',files:[file]})}catch(error){if(error.name!=='AbortError')toast('分享失败','error')} }else{$('downloadButton').click();toast('当前浏览器不支持系统分享，已改为下载','success')}};
}
updateStatus();renderHistory();bind();
if('serviceWorker'in navigator)state.serviceWorkerRegistration=navigator.serviceWorker.register('/sw.js').catch(()=>null);
if('Notification'in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{});
